# Generated by Django 4.2.11 on 2026-05-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'indexes': [models.Index(fields=['name'], name='cities_name_a7bf2e_idx'), models.Index(fields=['country'], name='cities_country_e9560c_idx')],
            },
        ),
    ]
