# Generated by Django 4.2.11 on 2026-05-10 04:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SIGHTSEEING', 'Sightseeing'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Accommodation'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_completed', models.BooleanField(default=False)),
                ('booking_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.tripstop')),
            ],
            options={
                'db_table': 'trip_activities',
                'indexes': [models.Index(fields=['trip_stop', 'date'], name='trip_activi_trip_st_33973c_idx'), models.Index(fields=['trip_stop', 'position'], name='trip_activi_trip_st_8db6e6_idx')],
            },
        ),
    ]
