# Generated by Django 4.2.11 on 2026-05-10 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripstop',
            old_name='notes',
            new_name='stop_notes',
        ),
        migrations.CreateModel(
            name='TripNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='trips.tripstop')),
            ],
            options={
                'db_table': 'trip_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trip', 'created_at'], name='trip_notes_trip_id_a5d2f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CLOTHING', 'Clothing'), ('DOCUMENTS', 'Documents'), ('ELECTRONICS', 'Electronics'), ('HEALTH', 'Health & Toiletries'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('is_packed', models.BooleanField(default=False)),
                ('is_essential', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_items', to='trips.tripstop')),
            ],
            options={
                'db_table': 'packing_items',
                'ordering': ['position', 'name'],
                'indexes': [models.Index(fields=['trip', 'is_packed'], name='packing_ite_trip_id_01c46c_idx'), models.Index(fields=['trip', 'category'], name='packing_ite_trip_id_4ec3c3_idx'), models.Index(fields=['trip', 'position'], name='packing_ite_trip_id_976bf8_idx')],
            },
        ),
    ]
