# Generated by Django 4.2.11 on 2026-05-10 04:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SIGHTSEEING', 'Sightseeing'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Accommodation'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTUAL', 'Actual')], default='PLANNED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.tripstop')),
            ],
            options={
                'db_table': 'budget_entries',
                'indexes': [models.Index(fields=['trip', 'category'], name='budget_entr_trip_id_3d0c94_idx'), models.Index(fields=['trip', 'entry_type'], name='budget_entr_trip_id_f2a220_idx')],
            },
        ),
    ]
